//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaWebE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra
    {
        public int CompraId { get; set; }
        public string NombreDelProducto { get; set; }
        public Nullable<int> CantidadCompra { get; set; }
        public Nullable<int> TotalCompraId { get; set; }
        public Nullable<System.DateTime> FechaCompra { get; set; }
        public Nullable<int> CodigoPId { get; set; }
        public Nullable<int> ProvedorCodigoId { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Provedor Provedor { get; set; }
    }
}
