//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaWebE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public string VentaProductoId { get; set; }
        public Nullable<int> CantidadVenta { get; set; }
        public Nullable<int> TotalVenta { get; set; }
        public Nullable<System.DateTime> FechaVenta { get; set; }
        public Nullable<int> ClienteCoId { get; set; }
        public Nullable<int> EmpleadoId { get; set; }
        public Nullable<int> CodigoPId { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
